// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtH-STKizCvRZRmRB_fO4LQQNobCSlnCw',
    appId: '1:565896068214:web:d7938d39c4f90823e83357',
    messagingSenderId: '565896068214',
    projectId: 'ai-business-manager-89107',
    authDomain: 'ai-business-manager-89107.firebaseapp.com',
    storageBucket: 'ai-business-manager-89107.firebasestorage.app',
    measurementId: 'G-ZXN7XEQG8K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkItOsYZH9nPC4wzbYSxCBaWF6Flo_myI',
    appId: '1:565896068214:android:6582502767b2d150e83357',
    messagingSenderId: '565896068214',
    projectId: 'ai-business-manager-89107',
    storageBucket: 'ai-business-manager-89107.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtRE0yK0UBi8Rf5YbD7RREjm2fG4hSTZs',
    appId: '1:565896068214:ios:ac147c81bfbcc179e83357',
    messagingSenderId: '565896068214',
    projectId: 'ai-business-manager-89107',
    storageBucket: 'ai-business-manager-89107.firebasestorage.app',
    iosBundleId: 'com.example.hackThisFall25',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtRE0yK0UBi8Rf5YbD7RREjm2fG4hSTZs',
    appId: '1:565896068214:ios:ac147c81bfbcc179e83357',
    messagingSenderId: '565896068214',
    projectId: 'ai-business-manager-89107',
    storageBucket: 'ai-business-manager-89107.firebasestorage.app',
    iosBundleId: 'com.example.hackThisFall25',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtH-STKizCvRZRmRB_fO4LQQNobCSlnCw',
    appId: '1:565896068214:web:fc13af732095de6ce83357',
    messagingSenderId: '565896068214',
    projectId: 'ai-business-manager-89107',
    authDomain: 'ai-business-manager-89107.firebaseapp.com',
    storageBucket: 'ai-business-manager-89107.firebasestorage.app',
    measurementId: 'G-DT1F2W9L23',
  );
}
