// lib/main.dart

import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:hack_this_fall_25/screens/home_screen.dart';
import 'firebase_options.dart'; // This file is generated by `flutterfire configure`
// A widget to handle login/logout logic

void main() async {
  // 1. Ensure Flutter bindings are initialized
  WidgetsFlutterBinding.ensureInitialized();

  // 2. This is the Firebase initialization you asked for.
  // It uses the firebase_options.dart file to get the
  // correct keys for whatever platform (iOS, Android, Web) you're running on.
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  // 3. Run the app, wrapped in a ProviderScope.
  // This is the root widget that allows Riverpod
  // to work everywhere in your app.
  runApp(const ProviderScope(child: MyApp()));
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'AI Business Manager',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(
          seedColor: Colors.deepPurple,
          brightness: Brightness.light,
        ),
        useMaterial3: true,
      ),
      darkTheme: ThemeData(
        colorScheme: ColorScheme.fromSeed(
          seedColor: Colors.deepPurple,
          brightness: Brightness.dark,
        ),
        useMaterial3: true,
      ),
      themeMode: ThemeMode.system, // Automatically switch theme
      debugShowCheckedModeBanner: false,

      // 4. Start at the AuthGate.
      // This widget will check if the user is logged in
      // and show either the LoginScreen or HomeScreen.
      home: HomeScreen(),
    );
  }
}
